import { z } from "zod";

export const formDocSchema = z.object({
  shipperName: z.string(),
  shipperAddress: z.string(),
  shipperCnpj: z.string(),
  consigneeName: z.string(),
  consigneeAddress: z.string(),
  brazilBiName: z.string(),
  brazilBiAddress: z.string(),
  brazilBiCep: z.string().optional(),
  brazilBiCnpj: z.string(),
  bookingNo: z.string(),
  blNumber: z.string(),
  containerCount: z.coerce.number().int().min(1).optional(),
  vessel: z.string(),
  portOfLoading: z.string(),
  portOfDischarge: z.string(),
  placeOfReceipt: z.string(),
  placeOfDelivery: z.string().optional(),
  containers: z.string(),
  containerType: z.string(),
  packages: z.string(),
  description: z.string(),
  ncm: z.string(),
  netWeight: z.string(),
  grossWeight: z.string(),
  measurement: z.string(),
  freightValue: z.string(),
  incoterm: z.enum(['FOB', 'CIF', 'CFR', 'EXW']),
  currency: z.enum(['USD', 'EUR', 'BRL']),
  beneficiaryBank: z.string(),
  beneficiaryAddress: z.string(),
  swiftCode: z.string(),
  accountNumber: z.string(),
  routingNumber: z.string(),
  correspondent: z.string(),
  invoiceNumber: z.string(),
  circular: z.string(),
  shippedOnBoardDate: z.string(),
  issueDate: z.string().optional(),
  paymentDate: z.string(),
  invoiceDate: z.string(),
  logoUrl: z.string().optional(),
  signatureUrl: z.string().optional(),
})

export type FormDocValues = z.infer<typeof formDocSchema>

export const DEFAULT_VALUES = {
  shipperName: 'AGG ASSESSORIA LTDA',
  shipperAddress: 'R DOUTOR PAULO JOSE DE AZEVEDO BONAVIDES, 1008 - 11.445-490 - JARDIM ACAPULCO - GUARUJÁ - SP',
  shipperCnpj: '43.651.382/0001-26',
  consigneeName: 'Alto Products Corp.',
  consigneeAddress: 'One Alto Way, Atmore, AL 36502, USA',
  brazilBiName: 'BRAZIL BUSINESS INTELLIGENCE COMEX LTDA',
  brazilBiAddress: 'AV VEREADOR ABRAHAO JOAO FRANCISCO, 2957 SALA 03 BOX 88 - RESSACADA - ITAJAÍ - SC',
  brazilBiCep: '88302-102',
  brazilBiCnpj: '54.438.731/0001-42',
  bookingNo: 'MEDUOK815514001US',
  blNumber: 'MEDUOK815514001US',
  containerCount: 6,
  vessel: 'KURE - UA505A',
  portOfLoading: 'NORFOLK, VA',
  portOfDischarge: 'RIO DE JANEIRO',
  placeOfReceipt: 'N/M',
  placeOfDelivery: '',
  containers: 'MSNU6511543 (1998544), TRHU7731937 (1998545), BEAU5669022 (1998548), MSMU4729194 (1998546), MSNU9697853 (1998547), FFAU2515733 (1998543)',
  containerType: '06X40 HC',
  packages: '55 Package(s) of (PALLETS)',
  description: 'F8.0MM 110KSI UTS 3.1 STEEL WIRE',
  ncm: '7217',
  netWeight: '18916',
  grossWeight: '106,818.000',
  measurement: '67.040',
  freightValue: '17.494,26',
  incoterm: 'FOB',
  currency: 'USD',
  beneficiaryBank: 'United Bank',
  beneficiaryAddress: '200 E. Nashville Ave Atmore, AL 36502, USA',
  swiftCode: 'FRNAUS44',
  accountNumber: '1620036291',
  routingNumber: '062102098',
  correspondent: 'FNBB',
  invoiceNumber: 'ALTOUSA-240108',
  circular: 'DB97798451',
  shippedOnBoardDate: '02/10/2025',
  issueDate: '02/10/2025',
  paymentDate: '3 DE DEZEMBRO DE 2025',
  invoiceDate: 'DEZ 3 2025',
}